version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.dev
    image: inventory:latest
    ports:
      - "7000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
